### ISSUE TITLE
Code partially broken after latest release

### ISSUE THREAD

**Issue by gbiavati** [Jarodiv/puppet-ffmpeg#4]
Dear Jarodiv,

Thanks for the great Job you are doing in maintaining this puppet module.
Recently you added a parameter _**$install_options**_ which is declared within an **if** statement.

Unfortunately the parameter is used also in case the` if  $facts['os']['release']['major'] == '8'` is false.
Or in general in case of '7' the module does not work any longer because _**$install_options**_ is not defined.

I hope this is enough for you to set a fix.
Currently I am using r10k and to have the module working I set:

mod 'jarodiv-ffmpeg', :git => 'https://github.com/jarodiv/puppet-ffmpeg.git', :commit => '2055c6e'

**Comment by Jarodiv** [comment]
Thanks for the report. I too found the issue when adding rspec tests.

Unfortunately the code doesn't work anymore anyway due to a recent update of the repository I am using (getting tons of missing dependencies now).

I'll soon create a new release, fixing the `$install_options` issue and also switching to a different repository ('rpmfusion-free'). Only drawback is, that the new repo only offers an older version of ffmpeg (v4.2.3 compared to 4.3.2 in 'epel-multimedia')

**Comment by Jarodiv** [comment]
The issue should be fixed with release v1.1.0
